### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by z3473** [116davinder/kafka-cluster-ansible#22]
[root@localhost ansible]# ansible-playbook roles/kafka-cluster-ansible/all.yml -e "inventory=all"
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
ERROR! A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead

The error appears to be in '/etc/ansible/roles/kafka-cluster-ansible/all.yml': line 3, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

javaVersion: 11
^ here

[root@localhost ansible]# cat /etc/ansible/roles/kafka-cluster-ansible/all.yml
---

javaVersion: 11
updateJava: false                                               # only when you need to update java version

useSystemFirewall: false

kafkaGroup: kafka
kafkaUser: kafka
kafkaGroupId: 7000
kafkaUserId: 7000

kafkaInstallDir: /kafka
kafkaDataDir: "{{ kafkaInstallDir }}/kafka-data"
kafkaLogDir: "{{ kafkaInstallDir }}/kafka-logs"

kafkaGcLogs: true
kafkaGcLogsLocation: "{{ kafkaLogDir }}"
kafkaGcLogFileCount: 5
kafkaGcLogFileSize: 10M # with optional K, M or G suffix

**Comment by 116davinder** [comment]
@z3473, 
first thing, this repo is a collection of ansible roles not one role.
Second thing, you trying to run `all.yml` as playbook for ansible which is not expected from ansible so it will fail with error you mentioned `ERROR! A playbook must be a list of plays` .

I would recommend you to create similar playbook like this `https://github.com/116davinder/kafka-cluster-ansible/blob/master/clusterSetup.yml` and run it.
Example: `ansible-playbook -i inventory/<environment>/cluster.ini clusterSetup.yml` if you need to pass variables then check reference.
or something like this
-e, --extra-vars[](https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-e)
set additional variables as key=value or YAML/JSON, if filename prepend with @

Ref: 
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-e
