### ISSUE TITLE
Not working with JAVA 11

### ISSUE THREAD

**Issue by ktibi** [116davinder/kafka-cluster-ansible#3]
Hello,

Great job for your project. Thx :)

Your override of run script for kafka can't work with Java 11. Need to modify the template about KAFKA_GC_LOG_OPTS.

`export KAFKA_GC_LOG_OPTS="-Xloggc:{{ kafkaLogDir }}/kafkaServer-gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M"`

TO 

`export KAFKA_GC_LOG_OPTS="-Xlog:gc*:file={{ kafkaLogDir }}/kafkaServer-gc.log:time,tags:filecount=10,filesize=102400"`

**Comment by 116davinder** [comment]
I haven't tested with java 11 yet,
thanks a lot for heads up.

**Comment by 116davinder** [comment]
Kafka Service will fail with below logs
```
Aug 08 18:59:07 kafka-server-start.sh[64853]: [0.002s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/elasticdata/kafka-logs/kafkaServer-gc.log instead.
Aug 08 18:59:07 kafka-server-start.sh[64853]: Unrecognized VM option 'PrintGCDateStamps'
Aug 08 18:59:07 kafka-server-start.sh[64853]: Error: Could not create the Java Virtual Machine.
Aug 08 18:59:07 kafka-server-start.sh[64853]: Error: A fatal exception has occurred. Program will exit.
Aug 08 18:59:07 systemd[1]: kafka.service: main process exited, code=exited, status=1/FAILURE
Aug 08 18:59:07 systemd[1]: kafka.service: control process exited, code=exited status=1
Aug 08 18:59:07 systemd[1]: Unit kafka.service entered failed state.
Aug 08 18:59:07 systemd[1]: kafka.service failed.
```
