### ISSUE TITLE
[bug] inconsistent usage of aws_kafka_ebs_device_fs variable

### ISSUE THREAD

**Issue by Ubun1** [116davinder/kafka-cluster-ansible#5]
https://github.com/116davinder/kafka-cluster-ansible/blob/102d828e56f84c7b19ffe1694ab6a829e6562a2e/roles/common/tasks/ebsDisk.yml#L28

Hello, it's possible a bug , because at https://github.com/116davinder/kafka-cluster-ansible/blob/102d828e56f84c7b19ffe1694ab6a829e6562a2e/roles/common/tasks/ebsDisk.yml#L15 line u use ```aws_kafka_ebs_device_fs``` variable to set fs type.

**Comment by 116davinder** [comment]
@Ubun1
Thanks a lot for reporting Issue, I will review it.
